# Generated by Django 3.2.4 on 2021-06-09 19:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title_text', models.CharField(max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, primary_key=True, serialize=False, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
